import React from 'react';
import { Metadata } from 'next';
import { getSymbolAlias } from '@/lib/symbol-utils';
import { JsonLd } from '@/components/seo/json-ld';
import Link from 'next/link';
import { ChevronLeft, Zap, Target, TrendingUp, TrendingDown, Info } from 'lucide-react';

interface SymbolPageProps {
  params: Promise<{ symbol: string }>;
}

// Metadata generation for high-impact social cards and search visibility
export async function generateMetadata(props: SymbolPageProps): Promise<Metadata> {
  const params = await props.params;
  const symbol = params.symbol.toUpperCase();
  const alias = getSymbolAlias(symbol);
  
  return {
    title: `${alias} Institutional Intelligence | RSIQ Pro Terminal`,
    description: `Real-time RSI, MACD, and Order Flow data for ${alias}. Institutional-grade signals and strategy score for professional trading.`,
    openGraph: {
      title: `${alias} Institutional Pulse | RSIQ Pro`,
      description: `View real-time signals and institutional alpha for ${alias}. Generated by Mindscape Analytics.`,
      images: [`https://rsiq.mindscapeanalytics.com/api/og/${params.symbol.toLowerCase()}`],
    },
    twitter: {
      card: 'summary_large_image',
      title: `${alias} Institutional Signal | RSIQ Pro`,
      description: `Real-time institutional alpha for ${alias}. Check target zones and strategy scores.`,
      images: [`https://rsiq.mindscapeanalytics.com/api/og/${params.symbol.toLowerCase()}`],
    },
  };
}

export default async function SymbolPage(props: SymbolPageProps) {
  const params = await props.params;
  const symbol = params.symbol.toUpperCase();
  const alias = getSymbolAlias(symbol);

  return (
    <div className="min-h-screen bg-[#05080F] text-slate-100 selection:bg-[#39FF14]/30 selection:text-[#39FF14]">
      {/* JSON-LD for Search Engines */}
      <JsonLd />
      
      {/* Top Decoration */}
      <div className="absolute top-0 left-0 w-full h-[300px] bg-gradient-to-b from-[#39FF14]/[0.05] to-transparent pointer-events-none" />

      <main className="relative max-w-4xl mx-auto px-6 py-12 md:py-24">
        {/* Navigation */}
        <Link 
          href="/" 
          className="inline-flex items-center gap-2 text-slate-500 hover:text-[#39FF14] transition-colors mb-8 group"
        >
          <ChevronLeft size={16} className="transition-transform group-hover:-translate-x-1" />
          <span className="text-xs font-black uppercase tracking-widest">Back to Hub</span>
        </Link>

        {/* Hero Section */}
        <div className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <span className="px-3 py-1 bg-[#39FF14]/10 text-[#39FF14] border border-[#39FF14]/20 rounded-sm text-[10px] font-black uppercase tracking-[0.2em] shadow-[0_0_15px_rgba(57,255,20,0.1)]">
              Institutional Intelligence
            </span>
            <div className="flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-[#39FF14] animate-pulse" />
                <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Live Engine Stream</span>
            </div>
          </div>

          <h1 className="text-5xl md:text-7xl font-black tracking-tighter mb-4 leading-tight">
            {alias} <span className="text-[#39FF14]">In Real-Time</span>.
          </h1>
          
          <p className="text-xl text-slate-400 max-w-2xl font-medium leading-relaxed">
            Institutional-grade multi-indicator analysis for <span className="text-white">{alias}</span>. 
            Deployed on the **Mindscape Matrix**, tracking whale orderflow and RSI divergences.
          </p>
        </div>

        {/* Intelligence Module */}
        <div className="grid lg:grid-cols-3 gap-6 mb-12">
          {/* Signal Preview Card */}
          <div className="lg:col-span-2 relative group p-1 bg-gradient-to-br from-white/10 to-transparent rounded-[2.5rem] overflow-hidden shadow-2xl transition-all hover:scale-[1.01]">
            <div className="absolute inset-0 bg-[#0A0D14]" />
            <div className="relative bg-[#0A0D14] rounded-[2.3rem] p-8 md:p-10 border border-white/5 flex flex-col h-full min-h-[400px]">
                <div className="flex items-center justify-between mb-8">
                    <div>
                        <h2 className="text-3xl font-black tracking-tight">{alias} / USDT</h2>
                        <span className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-600">Institutional Scanner</span>
                    </div>
                    <div className="px-4 py-1.5 rounded-full bg-white/5 border border-white/10 text-[10px] font-black text-[#39FF14] uppercase tracking-widest flex items-center gap-2">
                        <Zap size={10} fill="currentColor" />
                        Live Signal
                    </div>
                </div>

                <div className="flex-1">
                    {/* Real-time Ticker Chart Container */}
                    <div className="h-48 w-full bg-white/[0.01] rounded-2xl border border-white/5 mb-8 relative group/chart overflow-hidden">
                        <div className="absolute inset-0 flex items-center justify-center pointer-events-none z-10">
                            <div className="flex flex-col items-center opacity-40 group-hover/chart:opacity-100 transition-opacity">
                                <span className="text-[10px] font-black uppercase tracking-[0.4em] text-slate-500 mb-2">Alpha Stream Initializing</span>
                                <div className="flex gap-1">
                                    <div className="w-1 h-3 bg-[#39FF14]/40 animate-[bounce_1s_infinite]" />
                                    <div className="w-1 h-2 bg-[#39FF14]/40 animate-[bounce_1.2s_infinite]" />
                                    <div className="w-1 h-4 bg-[#39FF14]/40 animate-[bounce_0.8s_infinite]" />
                                </div>
                            </div>
                        </div>
                        {/* TradingView Mini Chart Embedded via ui.tsx component in real client app */}
                        <div className="absolute inset-0 grayscale opacity-20" />
                    </div>
                    
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                        <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 flex flex-col justify-center">
                            <span className="text-[9px] text-slate-600 font-black uppercase tracking-widest mb-1">RSI (15M)</span>
                            <span className="text-2xl font-mono text-white tracking-tighter">--.-</span>
                        </div>
                        <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 flex flex-col justify-center">
                            <span className="text-[9px] text-slate-600 font-black uppercase tracking-widest mb-1">MACD</span>
                            <span className="text-2xl font-mono text-white tracking-tighter">-.----</span>
                        </div>
                        <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 flex flex-col justify-center lg:col-span-2">
                            <span className="text-[9px] text-slate-600 font-black uppercase tracking-widest mb-1">Signal Status</span>
                            <span className="text-xs font-black uppercase tracking-widest text-[#39FF14] animate-pulse">Scanning Alpha Zones...</span>
                        </div>
                    </div>
                </div>

                {/* Viral Share Trigger */}
                <div className="mt-10 flex items-center gap-4">
                     <Link 
                       href="/terminal"
                       className="flex-1 py-5 bg-[#39FF14] text-black font-black uppercase tracking-tighter text-sm flex items-center justify-center gap-3 hover:scale-[1.02] active:scale-[0.98] transition-all shadow-[0_0_50px_rgba(57,255,20,0.2)]"
                     >
                       Unlock Core Terminal
                       <Zap size={16} fill="currentColor" />
                     </Link>
                </div>
            </div>
          </div>

          {/* Institutional Stats Sidebar */}
          <div className="flex flex-col gap-6">
             <div className="p-8 rounded-[2.5rem] bg-white/[0.02] border border-white/10 flex flex-col gap-4">
                <span className="text-[9px] font-black uppercase tracking-[0.3em] text-[#39FF14]">Market Hunter</span>
                <h3 className="text-xl font-black text-white">Share Intelligence</h3>
                <p className="text-xs text-slate-500 font-medium leading-relaxed">
                   Leverage institutional data cards on X. Your followers get real-time RSI alpha while you drive attribution.
                </p>
                <div className="mt-4 p-4 rounded-2xl bg-white/[0.03] border border-white/5 select-all cursor-pointer font-mono text-[10px] text-slate-400 hover:text-[#39FF14] transition-colors break-all">
                    https://rsiq.mindscapeanalytics.com/api/og/{params.symbol.toLowerCase()}
                </div>
                <span className="text-[8px] font-black uppercase text-slate-700 tracking-widest">Copy preview link for X / Telegram</span>
             </div>

             <div className="p-8 rounded-[2.5rem] bg-gradient-to-br from-amber-500/[0.05] to-transparent border border-amber-500/10 flex flex-col gap-4">
                <span className="text-[9px] font-black uppercase tracking-[0.3em] text-amber-500">Security Access</span>
                <h3 className="text-lg font-black text-white">Encryption Locked</h3>
                <p className="text-[10px] text-slate-400 font-medium leading-relaxed">
                   Full Order Flow Monitoring and Liquidation Heatmaps require an active Institutional key.
                </p>
                <Link href="/subscription" className="text-[10px] font-black uppercase text-amber-500 border-b border-amber-500/30 pb-0.5 self-start hover:border-amber-500 transition-all">
                    Upgrade to RSIQ Pro
                </Link>
             </div>
          </div>
        </div>

        {/* Feature Grid */}
        <div className="grid md:grid-cols-2 gap-8 mb-24">
           <div className="flex items-start gap-4 p-8 rounded-[2rem] bg-white/[0.01] border border-white/5 hover:bg-white/[0.03] transition-all">
             <div className="w-10 h-10 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center shrink-0">
                <Target size={20} className="text-emerald-400" />
             </div>
             <div>
               <h3 className="text-lg font-black mb-2 uppercase tracking-tight">Institutional Density</h3>
               <p className="text-slate-500 text-sm leading-relaxed font-medium">
                 Proprietary smoothing algorithms eliminate retail "noise" and identify precision entry signals on crypto, indices, and metals.
               </p>
             </div>
           </div>
           
           <div className="flex items-start gap-4 p-8 rounded-[2rem] bg-white/[0.01] border border-white/5 hover:bg-white/[0.03] transition-all">
             <div className="w-10 h-10 rounded-lg bg-blue-500/10 border border-blue-500/20 flex items-center justify-center shrink-0">
                <Zap size={20} className="text-blue-400" />
             </div>
             <div>
               <h3 className="text-lg font-black mb-2 uppercase tracking-tight">Direct Execution</h3>
               <p className="text-slate-500 text-sm leading-relaxed font-medium">
                 Sub-second WebSocket telemetry ensures your signals are valid for the active candle, providing the speed required for market hunting.
               </p>
             </div>
           </div>
        </div>
      </main>

      {/* Footer Branding */}
      <footer className="relative z-10 py-12 border-t border-white/5 text-center">
         <p className="text-[10px] text-slate-600 font-black uppercase tracking-[0.4em] mb-4">
           MINDSCAPE ANALYTICS LLC &copy; 2026
         </p>
         <div className="flex items-center justify-center gap-6 opacity-30">
            <Link href="/legal/terms" className="text-[9px] hover:text-white transition-colors uppercase font-bold tracking-widest">Terms</Link>
            <Link href="/legal/privacy" className="text-[9px] hover:text-white transition-colors uppercase font-bold tracking-widest">Privacy</Link>
         </div>
      </footer>
    </div>
  );
}
